name: Validate docker.config.yml against remote schema

on:
  push:
    paths:
      - "docker.config.yml"
  pull_request:
    paths:
      - "docker.config.yml"

jobs:
  schema-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Validate docker.config.yml against remote schema
        run: |
          check-jsonschema \
            --schemafile https://raw.githubusercontent.com/geopython/pygeoapi/refs/heads/master/pygeoapi/resources/schemas/config/pygeoapi-config-0.x.yml \
            docker.config.yml
